spring:
  datasource:
    url: jdbc:mysql://localhost:57694/sis_financeiro_despesa?createDatabaseIfNotExist=true
    username: root
    password: ${USER_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
